# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/flywheel-io/GRP-5-transfer-log-report:$CI_COMMIT_REF_NAME .
  except:
    - tags

test:
  stage: test
  script:
    - ./tests/bin/docker-test.sh

deploy:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/flywheel-io/GRP-5-transfer-log-report:$CI_COMMIT_REF_NAME
  only:
    - tag
